version: "3.9"

######### IMPORTANT #############
# This is my main docker-compose file with most of the apps. I run docker on other systems with smaller stacks (web and synology).
# You can copy-paste services from one docker-compose file in this repo to another to add other apps.

# Edit the .env file with the following variables
# DOMAINNAME_CLOUD_SERVER

# Create the following secret files
# cd ~/docker/secrets
# touch cf_token

##### SECRETS TO SET #####
# cf_token Zone/Zone/Read & Zone/DNS/Edit

########################### NETWORKS
# docker network create --subnet 192.168.90.0/24 npm_proxy

networks:
  npm_proxy:
    external: true
  authelia:
    external: false

########################### SECRETS
secrets:
  cf_token:
    file: $SECRETSDIR/cf_token

########################### EXTENSION FIELDS
# Helps eliminate repetition of sections
# More Info on how to use this: https://github.com/htpcBeginner/docker-traefik/pull/228

# Common environment values
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# Keys common to some of the services in basic-services.txt
x-common-keys-core: &common-keys-core
  networks:
    - npm_proxy
  security_opt:
    - no-new-privileges:true
  restart: always

########################### SERVICES
services:
  ############################# FRONTENDS

  # Nginx Proxy Manager - Reverse Proxy with LetsEncrypt
  npm:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    container_name: npm
    image: 'jc21/nginx-proxy-manager:latest'
    # For Static IP
    networks:
    # For Static IP
      npm_proxy:
        ipv4_address: 192.168.90.254 # You can specify a static IP
    # For Dynamic IP
    # networks:
    #  - npm_proxy
    ports:
      - '80:80' # Public HTTP Port. Port Forwarding on Router is ON.
      - '443:443' # Public HTTPS Port. Port Forwarding on Router is ON.
      - '81:81' # Admin Web Port. Port Forwarding on Router is OFF. Internal Home Network Access only - 192.168.89.254:81.
    volumes:
      - $APPDIR/npm/config:/config 
      - $APPDIR/npm/letsencrypt:/etc/letsencrypt
      - $APPDIR/npm/data:/data
      - $APPDIR/npm/snippets:/snippets
      - $SECRETSDIR:/secrets
    environment:
      <<: *default-tz-puid-pgid
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      DB_MYSQL_HOST: "npm-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "NPMu53r"
      DB_MYSQL_PASSWORD: /secrets/authelia_storage_postgres_password
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'

  npm-db:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    container_name: npm-db
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    networks:
      - npm_proxy
    environment:
      <<: *default-tz-puid-pgid
      MYSQL_ROOT_PASSWORD: /secrets/authelia_storage_encryption_key
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'NPMu53r'
      MYSQL_PASSWORD: /secrets/authelia_storage_postgres_password
    volumes:
      - $APPDIR/npm/mysql:/var/lib/mysql
      - $SECRETSDIR:/secrets

  authelia:
    <<: *common-keys-core
    container_name: authelia
    image: authelia/authelia:latest
    expose:
      - 9091
    volumes:
      - $APPDIR/authelia/config:/config
      - $SECRETSDIR:/secrets
    networks:
      - npm_proxy
      - authelia
    environment:
      <<: *default-tz-puid-pgid
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      AUTHELIA_JWT_SECRET_FILE: /secrets/authelia_jwt_secret
      AUTHELIA_SESSION_SECRET_FILE: /secrets/authelia_session_secret
      AUTHELIA_DUO_API_SECRET_KEY_FILE: /secrets/authelia_duo_api_secret_key
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /secrets/authelia_storage_postgres_password
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/authelia_storage_encryption_key
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /secrets/authelia_notifier_smtp_password
    restart: unless-stopped
    
  auth-redis:
    container_name: auth-redis
    image: redis:alpine
    expose:
      - 6379
    volumes:
      - $APPDIR/authelia/auth-redis:/data
      - $SECRETSDIR:/secrets
    environment:
      <<: *default-tz-puid-pgid
    networks:
      - authelia

  auth-db:
    container_name: auth-db
    image: postgres:alpine
    expose:
      - 3306
    volumes:
      - $APPDIR/authelia/auth-db:/data
      - $SECRETSDIR:/secrets
    environment:
      <<: *default-tz-puid-pgid
      POSTGRES_DB: authelia
      POSTGRES_USER: Au7h3l1au53r
      POSTGRES_PASSWORD_FILE: /secrets/authelia_storage_postgres_password
    networks:
      - authelia
    restart: always

  secure:
    image: traefik/whoami
    container_name: secure
    networks:
      - npm_proxy
    expose:
      - 80
    restart: unless-stopped

  public:
    image: traefik/whoami
    container_name: public
    networks:
      - npm_proxy
    expose:
      - 80
    restart: unless-stopped