version: "3.9"

networks:
  npm_proxy:
    external: true
  wordpress:
    external: false

##### SECRETS TO SET #####
### openssl rand -hex 64 ###
# cd ~/docker/secrets 
# touch mysql_root_password mysql_user mysql_password

########################### EXTENSION FIELDS
# Helps eliminate repetition of sections
# More Info on how to use this: https://github.com/htpcBeginner/docker-traefik/pull/228

# Common environment values
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# Keys common to some of the services in basic-services.txt
x-common-keys-core: &common-keys-core
  networks:
    - npm_proxy
  security_opt:
    - no-new-privileges:true
  restart: always

services:

  wordpress:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    image: wordpress:latest
    container_name: wordpress
    networks:
      npm_proxy:
      wordpress:
    expose:
      - 80
    restart: always
    volumes:
      - $APPDIR/wordpress/data:/var/www/html
      - $SECRETSDIR:/secrets
    environment:
      TZ: $TZ
      WORDPRESS_DB_HOST: wp-db:3306
      WORDPRESS_DB_NAME: wp-gycd-22
      WORDPRESS_DB_USER_FILE: /secrets/mysql_user
      WORDPRESS_DB_PASSWORD_FILE: /secrets/mysql_password
    depends_on:
      - wp-db

  wp-db:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    image: mariadb
    container_name: wp-db
    volumes:
      - $APPDIR/wordpress/db:/var/lib/mysql
      - $SECRETSDIR:/secrets
    networks:
      - wordpress
    restart: always
    environment:
      TZ: $TZ
      MYSQL_ROOT_PASSWORD_FILE: /secrets/mysql_root_password
      MYSQL_DATABASE: wp-gycd-22
      MYSQL_USER_FILE: /secrets/mysql_user
      MYSQL_PASSWORD_FILE: /secrets/mysql_password