version: "3.9"

# Hardcoded link to .env file outside yml directory
env_file:
  - /home/$USER/docker/.env

# Edit the .env file with the following variables 

# NPM_ROOT_DB_PASSWORD
# NPM_DB_PASSWORD
# DOMAINNAME

########################### NETWORKS
# There is no need to create any networks outside this docker-compose file.

networks:
  npm_proxy:
    external: true
  npm:
    external: false

########################### EXTENSION FIELDS
# Helps eliminate repetition of sections
# More Info on how to use this: https://github.com/htpcBeginner/docker-traefik/pull/228

# Keys common to some of the services in basic-services.txt
x-common-keys-core: &common-keys-core
  networks:
    - npm_proxy
  security_opt:
    - no-new-privileges:true
  restart: always

services:
  # Nginx Proxy Manager - Reverse Proxy with LetsEncrypt
  npm:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    container_name: npm
    image: 'jc21/nginx-proxy-manager:latest'
    # For Static IP
    # networks:
      # npm_proxy:
      #   ipv4_address: 192.168.90.254 # You can specify a static IP
      # npm:
    # For Dynamic IP
    networks:
      - npm_proxy
      - npm
    expose:
      - 80 # Public HTTP Port. Port Forwarding on Router is ON.
      - 443 # Public HTTPS Port. Port Forwarding on Router is ON.
      - 81 # Admin Web Port. Use 81 for NPM. Port Forwarding on Router is OFF. Internal Home Network Access only - 192.168.89.254:81.
    volumes: # Persistent volumes with bind mounts to easily move/backup data
      - $APPDIR/npm/config:/config
      - $APPDIR/npm/letsencrypt:/etc/letsencrypt
      - $APPDIR/npm/data:/data
      - $APPDIR/npm/snippets:/snippets
    environment:
      DB_MYSQL_HOST: "npm-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "NPMu53r"
      DB_MYSQL_PASSWORD: $NPM_DB_PASSWORD
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    labels:
      - homepage.group: Core
      - homepage.name: NGINX Proxy Manager
      - homepage.icon: npm.png
      - homepage.href: https://proxy.$DOMAINNAME/
      - homepage.widget.type: npm
      - homepage.widget.url: https://proxy.$DOMAINNAME/
      - homepage.widget.username: 
      - homepage.widget.password: 

  npm-db:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    container_name: npm-db
    image: mariadb:10
    networks:
      - npm
    environment:
      MARIADB_ROOT_PASSWORD: $NPM_ROOT_DB_PASSWORD
      MARIADB_DATABASE: "npm"
      MARIADB_USER: "NPMu53r"
      MARIADB_PASSWORD: $NPM_DB_PASSWORD
    volumes: # Persistent volumes with bind mounts to easily move/backup data
      - $APPDIR/npm/mysql:/var/lib/mysql